
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username: szabo-peter
    password: 123456
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: "update"